# Generated by Django 5.1.7 on 2025-04-04 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(default='benefactor-unknown', max_length=100)),
                ('donor_phone_number', models.CharField(blank=True, max_length=20)),
                ('donation_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('to_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
                'ordering': ['-donation_date'],
            },
        ),
    ]
